#:schema schema/Universe.toml.schema.json

# ==============================================================================
# DUNST APP CONFIGURATION (Put in default profile)
# ==============================================================================
[default.Dunst.global]
font = "JetBrainsMono Nerd Font 10"
width = 300
height = "(0, 300)"
origin = "top-right"
offset = "(20, 20)"
progress-bar = true
progress-bar-height = 10
progress-bar-frame-width = 1
progress-bar-min-width = 150
progress-bar-max-width = 300
corner-radius = 12
padding = 15
horizontal-padding = 15
frame-width = 2
gap-size = 8
separator-height = 2
sort = true
idle-threshold = 120
markup = "full"
format = "<b>%s</b>\n%b"
alignment = "left"
show-age-threshold = 60
word-wrap = true
ignore-newline = false
stack-duplicates = true
hide-duplicate-count = false
show-indicators = true
icon-position = "left"
min-icon-size = 32
max-icon-size = 64

[default.Dunst.urgency-low]
timeout = 3

[default.Dunst.urgency-normal]
timeout = 5

[default.Dunst.urgency-critical]
timeout = 0  # 0 means it will not expire until manually dismissed
